FROM node:lts-alpine

WORKDIR /app

RUN npm install -g json-server

CMD ["json-server", "--watch", "db.json", "--port", "3000", "--host", "0.0.0.0"]

# run
# docker run -p 3000:3000 -v ${PWD}:/app my-json-server